#source 'https://rubygems.org'

#gem 'awspec'
#gem 'rake'
#ruby '2.3.1'

source 'https://rubygems.org/' do
  gem 'kitchen-verifier-awspec'
  gem 'awspec'
  gem 'aws-sdk'
  gem 'test-kitchen'
  gem 'kitchen-terraform', :git => 'https://github.com/newcontext-oss/kitchen-terraform.git', :branch => 'v2.0.0'
end
